import os

class LibraryItem:
    """Base class representing a general item in the library."""
    def __init__(self, item_id, title):
        self.item_id = item_id
        self.title = title
        self.is_issued = False

    def issue(self):
        """Issues the item if it is currently available."""
        if not self.is_issued:
            self.is_issued = True
            return True
        return False

    def return_item(self):
        """Returns the item to the library if it was issued."""
        if self.is_issued:
            self.is_issued = False
            return True
        return False

    def get_details(self):
        """Polymorphic method to be overridden by derived classes."""
        raise NotImplementedError("Subclasses must implement abstract method get_details()")


class Book(LibraryItem):
    """Derived class for Books."""
    def __init__(self, item_id, title, author, isbn):
        super().__init__(item_id, title)
        self.author = author
        self.isbn = isbn

    def get_details(self):
        status = "Issued" if self.is_issued else "Available"
        return f"[Book]      ID: {self.item_id:<6} | Title: {self.title:<25} | Author: {self.author:<18} | ISBN: {self.isbn} | Status: {status}"


class Magazine(LibraryItem):
    """Derived class for Magazines."""
    def __init__(self, item_id, title, issue_number, month):
        super().__init__(item_id, title)
        self.issue_number = issue_number
        self.month = month

    def get_details(self):
        status = "Issued" if self.is_issued else "Available"
        return f"[Magazine]  ID: {self.item_id:<6} | Title: {self.title:<25} | Issue No: {str(self.issue_number):<15} | Month: {self.month:<10} | Status: {status}"


class Journal(LibraryItem):
    """Derived class for Academic Journals."""
    def __init__(self, item_id, title, volume, field):
        super().__init__(item_id, title)
        self.volume = volume
        self.field = field

    def get_details(self):
        status = "Issued" if self.is_issued else "Available"
        return f"[Journal]   ID: {self.item_id:<6} | Title: {self.title:<25} | Volume: {str(self.volume):<15} | Field: {self.field:<10} | Status: {status}"


def run_library_system(output_filename):
    """Initializes catalogue items, performs issue/return transactions, 
    and saves the comprehensive report to an output file.
    """
    main_script_name = os.path.basename(__file__)
    
    # Initializing diverse library items
    items = [
        Book("B001", "The Python Cookbook", "David Beazley", "978-0134032822"),
        Book("B002", "Clean Code", "Robert C. Martin", "978-0132350884"),
        Magazine("M001", "National Geographic", 204, "Aug 2026"),
        Journal("J001", "IEEE Transactions on AI", 15, "Tech")
    ]
    
    report_lines = []
    
    # Building structured report headers
    report_lines.append("LIBRARY MANAGEMENT SYSTEM REPORT\n")
    report_lines.append(f"Generated by Script: {main_script_name}\n")
    report_lines.append("=" * 110 + "\n")
    report_lines.append("1. INITIAL INVENTORY DETAILS\n")
    report_lines.append("-" * 110 + "\n")
    
    for item in items:
        report_lines.append(item.get_details() + "\n")
        
    report_lines.append("\n" + "=" * 110 + "\n")
    report_lines.append("2. TRANSACTION LOG (ISSUE & RETURN OPERATIONS)\n")
    report_lines.append("-" * 110 + "\n")
    
    # Simulating operations
    if items[0].issue():
        report_lines.append(f"-> SUCCESS: Book '{items[0].title}' (ID: {items[0].item_id}) was successfully issued.\n")
        
    if not items[0].issue():
        report_lines.append(f"-> NOTICE:  Book '{items[0].title}' (ID: {items[0].item_id}) is already issued and cannot be re-issued.\n")
        
    if items[2].issue():
        report_lines.append(f"-> SUCCESS: Magazine '{items[2].title}' (ID: {items[2].item_id}) was successfully issued.\n")
        
    if items[0].return_item():
        report_lines.append(f"-> SUCCESS: Book '{items[0].title}' (ID: {items[0].item_id}) was successfully returned to the library.\n")
        
    report_lines.append("\n" + "=" * 110 + "\n")
    report_lines.append("3. FINAL INVENTORY STATUS\n")
    report_lines.append("-" * 110 + "\n")
    
    for item in items:
        report_lines.append(item.get_details() + "\n")
        
    report_lines.append("=" * 110 + "\n")
    
    # Writing output to file
    try:
        with open(output_filename, 'w') as outfile:
            outfile.writelines(report_lines)
        print(f"Library execution complete. Results successfully written to '{output_filename}'.")
    except Exception as e:
        print(f"Error writing to output file: {e}")


if __name__ == "__main__":
    output_file = "library_activity_report.txt"
    run_library_system(output_file)