import numpy as np
import os

def analyze_student_performance(output_filename):
    """Computes total, average, and percentage improvement using NumPy vectorized operations,
    and writes the comprehensive analysis to a text file.
    """
    main_script_name = os.path.basename(__file__)
    
    # Defining student labels and subjects
    students = ["S1", "S2", "S3", "S4", "S5"]
    subjects = ["Mathematics", "Physics", "Chemistry", "English"]
    
    # NumPy arrays for Mid-Semester and End-Semester marks (Shape: 5 students x 4 subjects)
    mid_sem = np.array([
        [65, 70, 68, 72],
        [78, 75, 80, 77],
        [55, 60, 58, 62],
        [82, 85, 80, 88],
        [70, 68, 72, 74]
    ])
    
    end_sem = np.array([
        [72, 78, 75, 80],
        [84, 82, 86, 83],
        [65, 68, 66, 70],
        [88, 90, 85, 92],
        [78, 75, 80, 82]
    ])
    
    # Vectorized Calculations using NumPy
    mid_total = np.sum(mid_sem, axis=1)
    mid_avg = np.mean(mid_sem, axis=1)
    
    end_total = np.sum(end_sem, axis=1)
    end_avg = np.mean(end_sem, axis=1)
    
    # Percentage improvement calculation across total marks
    percentage_improvement = ((end_total - mid_total) / mid_total) * 100
    
    # Building report lines
    report_lines = []
    report_lines.append("STUDENT ACADEMIC PERFORMANCE & IMPROVEMENT ANALYSIS\n")
    report_lines.append(f"Generated by Script: {main_script_name}\n")
    report_lines.append("=" * 90 + "\n")
    
    # Header format
    header = f"{'Student':<10} {'Mid Total':<12} {'Mid Avg':<10} {'End Total':<12} {'End Avg':<10} {'Improvement (%)':<15}\n"
    report_lines.append(header)
    report_lines.append("-" * 90 + "\n")
    
    for i, student in enumerate(students):
        row = f"{student:<10} {mid_total[i]:<12} {mid_avg[i]:<10.2f} {end_total[i]:<12} {end_avg[i]:<10.2f} {percentage_improvement[i]:<15.2f}%\n"
        report_lines.append(row)
        
    report_lines.append("=" * 90 + "\n")
    
    # Subject-wise average summary
    sub_mid_avg = np.mean(mid_sem, axis=0)
    sub_end_avg = np.mean(end_sem, axis=0)
    
    report_lines.append("\nSUBJECT-WISE AVERAGE PERFORMANCE COMPARISON\n")
    report_lines.append("-" * 60 + "\n")
    sub_header = f"{'Subject':<15} {'Mid-Sem Avg':<15} {'End-Sem Avg':<15}\n"
    report_lines.append(sub_header)
    report_lines.append("-" * 60 + "\n")
    
    for j, subj in enumerate(subjects):
        sub_row = f"{subj:<15} {sub_mid_avg[j]:<15.2f} {sub_end_avg[j]:<15.2f}\n"
        report_lines.append(sub_row)
        
    report_lines.append("=" * 60 + "\n")
    
    # Write output to file
    try:
        with open(output_filename, 'w') as outfile:
            outfile.writelines(report_lines)
        print(f"NumPy analysis complete. Results written to '{output_filename}'.")
    except Exception as e:
        print(f"Error writing output file: {e}")

if __name__ == "__main__":
    output_file = "student_performance_report.txt"
    analyze_student_performance(output_file)