import numpy as np
import math
import os

# ---------------------------------------------------------------------------
# Custom Functions (Without NumPy)
# ---------------------------------------------------------------------------
def calculate_mean(data):
    return sum(data) / len(data)

def calculate_median(data):
    sorted_data = sorted(data)
    n = len(sorted_data)
    mid = n // 2
    if n % 2 == 0:
        return (sorted_data[mid - 1] + sorted_data[mid]) / 2
    else:
        return sorted_data[mid]

def calculate_std(data, mean_val):
    # Population standard deviation formula
    variance = sum((x - mean_val) ** 2 for x in data) / len(data)
    return math.sqrt(variance)

def calculate_min(data):
    m = data[0]
    for x in data:
        if x < m:
            m = x
    return m

def calculate_max(data):
    m = data[0]
    for x in data:
        if x > m:
            m = x
    return m


def run_statistical_analysis(output_filename):
    """Computes statistical measures with and without NumPy for multiple datasets,
    and formats the output neatly into a text file.
    """
    main_script_name = os.path.basename(__file__)
    
    datasets = {
        "Student Marks": [78, 85, 92, 67, 88, 73, 95, 81, 76, 89],
        "Temperatures (°C)": [28.5, 30.2, 29.8, 31.4, 27.9, 32.1, 30.5],
        "Sales Data ($)": [12500, 13800, 14200, 11900, 15100, 14750, 16000]
    }
    
    report_lines = []
    report_lines.append("STATISTICAL MEASURES COMPARISON REPORT\n")
    report_lines.append(f"Generated by Script: {main_script_name}\n")
    report_lines.append("=" * 80 + "\n\n")
    
    for name, data in datasets.items():
        # --- Computations Without NumPy ---
        native_mean = calculate_mean(data)
        native_median = calculate_median(data)
        native_std = calculate_std(data, native_mean)
        native_min = calculate_min(data)
        native_max = calculate_max(data)
        
        # --- Computations Using NumPy ---
        arr = np.array(data)
        np_mean = np.mean(arr)
        np_median = np.median(arr)
        np_std = np.std(arr)  # Default ddof=0 (population standard deviation)
        np_min = np.min(arr)
        np_max = np.max(arr)
        
        # Formatting section for each dataset
        report_lines.append(f"DATASET: {name}\n")
        report_lines.append(f"Raw Data: {data}\n")
        report_lines.append("-" * 80 + "\n")
        report_lines.append(f"{'Metric':<20} {'Without NumPy (Native)':<30} {'With NumPy':<30}\n")
        report_lines.append("-" * 80 + "\n")
        report_lines.append(f"{'Mean':<20} {native_mean:<30.4f} {np_mean:<30.4f}\n")
        report_lines.append(f"{'Median':<20} {native_median:<30.4f} {np_median:<30.4f}\n")
        report_lines.append(f"{'Standard Dev':<20} {native_std:<30.4f} {np_std:<30.4f}\n")
        report_lines.append(f"{'Minimum':<20} {native_min:<30} {np_min:<30}\n")
        report_lines.append(f"{'Maximum':<20} {native_max:<30} {np_max:<30}\n")
        report_lines.append("=" * 80 + "\n\n")
        
    try:
        with open(output_filename, 'w') as outfile:
            outfile.writelines(report_lines)
        print(f"Analysis complete. Results written successfully to '{output_filename}'.")
    except Exception as e:
        print(f"Error writing to output file: {e}")

if __name__ == "__main__":
    output_file = "statistical_report.txt"
    run_statistical_analysis(output_file)