import numpy as np
import os

# ---------------------------------------------------------------------------
# Matrix Operations Without NumPy (Pure Python using Nested Lists)
# ---------------------------------------------------------------------------
def native_add(A, B):
    return [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

def native_subtract(A, B):
    return [[A[i][j] - B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

def native_multiply(A, B):
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])
    if cols_A != rows_B:
        raise ValueError("Incompatible dimensions for multiplication")
    
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]
    return result

def native_transpose(A):
    return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]


def format_matrix(matrix):
    """Helper to convert a matrix to a clean string block."""
    return "\n".join(["  " + " ".join(f"{val:>6}" for val in row) for row in matrix])


def run_matrix_program(output_filename):
    main_script_name = os.path.basename(__file__)
    
    # Sample Input Matrices
    list_A = [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
    
    list_B = [
        [9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]
    ]
    
    report_lines = []
    report_lines.append("MATRIX OPERATIONS COMPARISON REPORT\n")
    report_lines.append(f"Generated by Script: {main_script_name}\n")
    report_lines.append("=" * 80 + "\n\n")
    
    report_lines.append("INPUT MATRIX A:\n")
    report_lines.append(format_matrix(list_A) + "\n\n")
    report_lines.append("INPUT MATRIX B:\n")
    report_lines.append(format_matrix(list_B) + "\n\n")
    report_lines.append("=" * 80 + "\n\n")
    
    # ---------------------------------------------------------------------------
    # 1. MATRIX ADDITION
    # ---------------------------------------------------------------------------
    native_add_res = native_add(list_A, list_B)
    
    arr_A = np.array(list_A)
    arr_B = np.array(list_B)
    np_add_res = arr_A + arr_B
    
    report_lines.append("1. MATRIX ADDITION (A + B)\n")
    report_lines.append("-" * 40 + "\n")
    report_lines.append("Without NumPy:\n" + format_matrix(native_add_res) + "\n\n")
    report_lines.append("With NumPy:\n" + format_matrix(np_add_res.tolist()) + "\n\n")
    report_lines.append("=" * 80 + "\n\n")
    
    # ---------------------------------------------------------------------------
    # 2. MATRIX SUBTRACTION
    # ---------------------------------------------------------------------------
    native_sub_res = native_subtract(list_A, list_B)
    np_sub_res = arr_A - arr_B
    
    report_lines.append("2. MATRIX SUBTRACTION (A - B)\n")
    report_lines.append("-" * 40 + "\n")
    report_lines.append("Without NumPy:\n" + format_matrix(native_sub_res) + "\n\n")
    report_lines.append("With NumPy:\n" + format_matrix(np_sub_res.tolist()) + "\n\n")
    report_lines.append("=" * 80 + "\n\n")
    
    # ---------------------------------------------------------------------------
    # 3. MATRIX MULTIPLICATION
    # ---------------------------------------------------------------------------
    native_mul_res = native_multiply(list_A, list_B)
    np_mul_res = np.dot(arr_A, arr_B)
    
    report_lines.append("3. MATRIX MULTIPLICATION (A * B)\n")
    report_lines.append("-" * 40 + "\n")
    report_lines.append("Without NumPy:\n" + format_matrix(native_mul_res) + "\n\n")
    report_lines.append("With NumPy:\n" + format_matrix(np_mul_res.tolist()) + "\n\n")
    report_lines.append("=" * 80 + "\n\n")
    
    # ---------------------------------------------------------------------------
    # 4. MATRIX TRANSPOSE
    # ---------------------------------------------------------------------------
    native_trans_res = native_transpose(list_A)
    np_trans_res = arr_A.T
    
    report_lines.append("4. MATRIX TRANSPOSE (Matrix A Transposed)\n")
    report_lines.append("-" * 40 + "\n")
    report_lines.append("Without NumPy:\n" + format_matrix(native_trans_res) + "\n\n")
    report_lines.append("With NumPy:\n" + format_matrix(np_trans_res.tolist()) + "\n\n")
    report_lines.append("=" * 80 + "\n")
    
    try:
        with open(output_filename, 'w') as outfile:
            outfile.writelines(report_lines)
        print(f"Matrix calculations complete. Results written successfully to '{output_filename}'.")
    except Exception as e:
        print(f"Error writing to output file: {e}")

if __name__ == "__main__":
    output_file = "matrix_operations_report.txt"
    run_matrix_program(output_file)