import numpy as np
import os

def format_matrix(matrix):
    """Helper to format a matrix or array neatly into a text block."""
    return "\n".join(["  " + " ".join(f"{val:>10.4f}" for val in row) for row in matrix])

def compute_matrix_properties(output_filename):
    main_script_name = os.path.basename(__file__)
    
    # Defining a square matrix (non-singular, so inverse and determinant are well-defined)
    matrix_A = np.array([
        [4, 2, 1],
        [3, 8, 2],
        [1, 1, 6]
    ], dtype=float)
    
    # Computations using NumPy's Linear Algebra module (numpy.linalg)
    determinant = np.linalg.det(matrix_A)
    rank = np.linalg.matrix_rank(matrix_A)
    
    try:
        inverse = np.linalg.inv(matrix_A)
        inverse_status = format_matrix(inverse)
    except np.linalg.LinAlgError:
        inverse_status = "Matrix is singular and cannot be inverted."

    # Preparing the report content
    report_lines = []
    report_lines.append("MATRIX LINEAR ALGEBRA ANALYSIS REPORT\n")
    report_lines.append(f"Generated by Script: {main_script_name}\n")
    report_lines.append("=" * 80 + "\n\n")
    
    report_lines.append("INPUT MATRIX A:\n")
    report_lines.append(format_matrix(matrix_A) + "\n\n")
    report_lines.append("=" * 80 + "\n\n")
    
    report_lines.append("1. DETERMINANT\n")
    report_lines.append("-" * 40 + "\n")
    report_lines.append(f"det(A) = {determinant:.4f}\n\n")
    report_lines.append("=" * 80 + "\n\n")
    
    report_lines.append("2. MATRIX RANK\n")
    report_lines.append("-" * 40 + "\n")
    report_lines.append(f"rank(A) = {rank}\n\n")
    report_lines.append("=" * 80 + "\n\n")
    
    report_lines.append("3. MATRIX INVERSE (A^-1)\n")
    report_lines.append("-" * 40 + "\n")
    if isinstance(inverse_status, str) and "singular" in inverse_status:
        report_lines.append(inverse_status + "\n\n")
    else:
        report_lines.append(inverse_status + "\n\n")
        
    report_lines.append("=" * 80 + "\n")
    
    # Writing to file
    try:
        with open(output_filename, 'w') as outfile:
            outfile.writelines(report_lines)
        print(f"Linear algebra computations complete. Results successfully written to '{output_filename}'.")
    except Exception as e:
        print(f"Error writing to output file: {e}")

if __name__ == "__main__":
    output_file = "matrix_linalg_report.txt"
    compute_matrix_properties(output_file)