import numpy as np
import os

def format_matrix(matrix):
    """Helper to format a 2D array neatly into a text block."""
    return "\n".join(["  " + " ".join(f"{val:>10.4f}" for val in row) for row in matrix])

def format_vector(vector):
    """Helper to format a 1D array/vector neatly."""
    return "  " + " ".join(f"{val:>10.4f}" for val in vector)

def compute_eigen_properties(output_filename):
    main_script_name = os.path.basename(__file__)
    
    # Defining a square matrix for eigenvalue and eigenvector decomposition
    matrix_A = np.array([
        [4, -2],
        [1,  1]
    ], dtype=float)
    
    # Computing eigenvalues and eigenvectors using NumPy's Linear Algebra module
    eigenvalues, eigenvectors = np.linalg.eig(matrix_A)
    
    # Preparing the report content
    report_lines = []
    report_lines.append("EIGENVALUE & EIGENVECTOR ANALYSIS REPORT\n")
    report_lines.append(f"Generated by Script: {main_script_name}\n")
    report_lines.append("=" * 80 + "\n\n")
    
    report_lines.append("INPUT MATRIX A:\n")
    report_lines.append(format_matrix(matrix_A) + "\n\n")
    report_lines.append("=" * 80 + "\n\n")
    
    report_lines.append("1. EIGENVALUES\n")
    report_lines.append("-" * 40 + "\n")
    for i, val in enumerate(eigenvalues):
        report_lines.append(f"Lambda_{i+1} = {val.real:.4f}\n")
    report_lines.append("\n" + "=" * 80 + "\n\n")
    
    report_lines.append("2. EIGENVECTORS (Columns corresponding to Eigenvalues)\n")
    report_lines.append("-" * 40 + "\n")
    report_lines.append(format_matrix(eigenvectors) + "\n\n")
    report_lines.append("=" * 80 + "\n\n")
    
    report_lines.append("3. VERIFICATION (A * v = lambda * v)\n")
    report_lines.append("-" * 40 + "\n")
    for i in range(len(eigenvalues)):
        v = eigenvectors[:, i]
        lhs = np.dot(matrix_A, v)
        rhs = eigenvalues[i] * v
        report_lines.append(f"For Lambda_{i+1} = {eigenvalues[i]:.4f}:\n")
        report_lines.append(f"  A * v     = [{lhs[0]:.4f}, {lhs[1]:.4f}]\n")
        report_lines.append(f"  Lambda * v = [{rhs[0]:.4f}, {rhs[1]:.4f}]\n\n")
        
    report_lines.append("=" * 80 + "\n")
    
    # Writing to file
    try:
        with open(output_filename, 'w') as outfile:
            outfile.writelines(report_lines)
        print(f"Eigen analysis complete. Results successfully written to '{output_filename}'.")
    except Exception as e:
        print(f"Error writing to output file: {e}")

if __name__ == "__main__":
    output_file = "eigen_analysis_report.txt"
    compute_eigen_properties(output_file)