import numpy as np
from scipy.integrate import quad
from scipy.optimize import approx_fprime
import os

def run_calculus_analysis(output_filename):
    """Performs numerical differentiation and integration using SciPy
    and saves a cleanly formatted report to an output file.
    """
    main_script_name = os.path.basename(__file__)
    
    # Define a sample mathematical function: f(x) = sin(x) * exp(x)
    def f(x):
        return np.sin(x) * np.exp(x)
    
    # Wrapper for approx_fprime (requires 1D array input)
    def f_scalar(x_arr):
        return np.sin(x_arr[0]) * np.exp(x_arr[0])
    
    report_lines = []
    report_lines.append("NUMERICAL DIFFERENTIATION & INTEGRATION REPORT (SCIPY)\n")
    report_lines.append(f"Generated by Script: {main_script_name}\n")
    report_lines.append("=" * 85 + "\n\n")
    
    report_lines.append("Target Function: f(x) = sin(x) * exp(x)\n")
    report_lines.append("-" * 85 + "\n\n")
    
    # ---------------------------------------------------------------------------
    # 1. NUMERICAL DIFFERENTIATION
    # ---------------------------------------------------------------------------
    report_lines.append("1. NUMERICAL DIFFERENTIATION (using scipy.optimize.approx_fprime)\n")
    report_lines.append("-" * 85 + "\n")
    report_lines.append(f"{'Point (x)':<15} {'Computed Derivative':<25} {'Analytical Derivative':<25}\n")
    report_lines.append("-" * 85 + "\n")
    
    test_points = [0.0, 1.0, 1.5708, 2.0]  # 1.5708 is approximately pi/2
    for x_val in test_points:
        x_arr = np.array([x_val])
        # SciPy numerical derivative approximation
        comp_deriv = approx_fprime(x_arr, f_scalar, 1e-6)[0]
        # Analytical derivative: f'(x) = exp(x) * (cos(x) + sin(x))
        anal_deriv = np.exp(x_val) * (np.cos(x_val) + np.sin(x_val))
        
        report_lines.append(f"{x_val:<15.4f} {comp_deriv:<25.6f} {anal_deriv:<25.6f}\n")
        
    report_lines.append("\n" + "=" * 85 + "\n\n")
    
    # ---------------------------------------------------------------------------
    # 2. NUMERICAL INTEGRATION
    # ---------------------------------------------------------------------------
    report_lines.append("2. NUMERICAL INTEGRATION (using scipy.integrate.quad)\n")
    report_lines.append("-" * 85 + "\n")
    report_lines.append(f"{'Interval [a, b]':<20} {'Computed Integral':<25} {'Estimated Error':<25}\n")
    report_lines.append("-" * 85 + "\n")
    
    intervals = [
        (0.0, np.pi),
        (0.0, 1.5708),
        (1.0, 3.0)
    ]
    
    for a, b in intervals:
        integral_val, abs_error = quad(f, a, b)
        interval_str = f"[{a:.2f}, {b:.2f}]"
        report_lines.append(f"{interval_str:<20} {integral_val:<25.6f} {abs_error:<25.2e}\n")
        
    report_lines.append("=" * 85 + "\n")
    
    try:
        with open(output_filename, 'w') as outfile:
            outfile.writelines(report_lines)
        print(f"Calculus analysis complete. Results successfully written to '{output_filename}'.")
    except Exception as e:
        print(f"Error writing to output file: {e}")

if __name__ == "__main__":
    output_file = "calculus_report.txt"
    run_calculus_analysis(output_file)