import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt
import os

def run_curve_fitting(output_filename, plot_filename):
    """Fits a second-degree polynomial to data using SciPy curve_fit,
    saves the coefficients to a text report, and generates a visualization plot.
    """
    main_script_name = os.path.basename(__file__)
    
    # Input data points
    x = np.array([1, 2, 3, 4, 5, 6], dtype=float)
    y = np.array([6, 17, 34, 57, 86, 121], dtype=float)
    
    # Define a second-degree polynomial model: f(x) = a*x^2 + b*x + c
    def objective_func(x_val, a, b, c):
        return a * (x_val ** 2) + b * x_val + c
    
    # Perform curve fitting using SciPy's optimize.curve_fit
    popt, pcov = curve_fit(objective_func, x, y)
    a_est, b_est, c_est = popt
    
    # Generate smooth points for plotting the fitted curve
    x_smooth = np.linspace(x[0], x[-1], 200)
    y_smooth = objective_func(x_smooth, a_est, b_est, c_est)
    
    # --- Generate Plot ---
    plt.figure(figsize=(8, 5))
    plt.scatter(x, y, color='red', s=60, zorder=5, label='Original Data Points')
    plt.plot(x_smooth, y_smooth, color='blue', linewidth=2, label=f'Fitted Curve: $y = {a_est:.2f}x^2 + {b_est:.2f}x + {c_est:.2f}$')
    plt.title('Second-Degree Polynomial Curve Fitting (SciPy)', fontsize=12, fontweight='bold')
    plt.xlabel('X Values', fontsize=10)
    plt.ylabel('Y Values', fontsize=10)
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.legend(fontsize=10)
    plt.tight_layout()
    plt.savefig(plot_filename, dpi=300)
    plt.close()
    
    # --- Build Text Report ---
    report_lines = []
    report_lines.append("POLYNOMIAL CURVE FITTING REPORT (SCIPY)\n")
    report_lines.append(f"Generated by Script: {main_script_name}\n")
    report_lines.append("=" * 80 + "\n\n")
    
    report_lines.append("1. INPUT DATA POINTS\n")
    report_lines.append("-" * 40 + "\n")
    report_lines.append(f"{'X':<10} {'Y':<10}\n")
    report_lines.append("-" * 40 + "\n")
    for xi, yi in zip(x, y):
        report_lines.append(f"{xi:<10.1f} {yi:<10.1f}\n")
    report_lines.append("\n" + "=" * 80 + "\n\n")
    
    report_lines.append("2. ESTIMATED POLYNOMIAL COEFFICIENTS (y = ax^2 + bx + c)\n")
    report_lines.append("-" * 40 + "\n")
    report_lines.append(f"Coefficient a (x^2) = {a_est:.4f}\n")
    report_lines.append(f"Coefficient b (x)   = {b_est:.4f}\n")
    report_lines.append(f"Coefficient c       = {c_est:.4f}\n\n")
    report_lines.append(f"Fitted Equation: y = {a_est:.4f}x^2 + {b_est:.4f}x + {c_est:.4f}\n\n")
    report_lines.append("=" * 80 + "\n")
    
    try:
        with open(output_filename, 'w') as outfile:
            outfile.writelines(report_lines)
        print(f"Curve fitting complete. Report saved to '{output_filename}' and plot saved to '{plot_filename}'.")
    except Exception as e:
        print(f"Error writing to output file: {e}")

if __name__ == "__main__":
    output_file = "curve_fitting_report.txt"
    plot_file = "fitted_curve_plot.png"
    run_curve_fitting(output_file, plot_file)