from scipy.optimize import minimize
import os

def run_optimization(output_filename):
    """Finds the minimum value of a multivariable function using SciPy optimization
    and saves the results to a text report.
    """
    main_script_name = os.path.basename(__file__)
    
    # Define the objective function: f(x, y) = (x - 2)^2 + (y - 2)^2
    def objective_function(vars):
        x, y = vars
        return (x - 2)**2 + (y - 2)**2
    
    # Initial guess for optimization
    initial_guess = [0.0, 0.0]
    
    # Perform optimization using BFGS method
    result = minimize(objective_function, initial_guess, method='BFGS')
    
    optimal_x, optimal_y = result.x
    min_value = result.fun
    
    # Build text report
    report_lines = []
    report_lines.append("FUNCTION OPTIMIZATION REPORT (SCIPY)\n")
    report_lines.append(f"Generated by Script: {main_script_name}\n")
    report_lines.append("=" * 80 + "\n\n")
    
    report_lines.append("Target Function: f(x, y) = (x - 2)^2 + (y - 2)^2\n")
    report_lines.append("-" * 80 + "\n\n")
    
    report_lines.append("1. OPTIMIZATION RESULTS\n")
    report_lines.append("-" * 40 + "\n")
    report_lines.append(f"Initial Guess:     {initial_guess}\n")
    report_lines.append(f"Optimal Point (x): {optimal_x:.6f}\n")
    report_lines.append(f"Optimal Point (y): {optimal_y:.6f}\n")
    report_lines.append(f"Minimum Value:     {min_value:.6f}\n\n")
    report_lines.append(f"Optimization Status: {result.message}\n")
    report_lines.append(f"Iterations:        {result.nit}\n")
    report_lines.append("=" * 80 + "\n")
    
    try:
        with open(output_filename, 'w') as outfile:
            outfile.writelines(report_lines)
        print(f"Optimization complete. Results successfully written to '{output_filename}'.")
    except Exception as e:
        print(f"Error writing to output file: {e}")

if __name__ == "__main__":
    output_file = "optimization_report.txt"
    run_optimization(output_file)